# SPDX-License-Identifier: CC0-1.0
name: Link check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Check README links
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: >-
            README.md
            --exclude-mail
            --exclude 'reddit\\.com|coq\\.inria\\.fr|sciencedirect\\.com'
            --accept 200,429
          fail: true
